version: '3'
services:
  db:
    build:
      context: ./docker-db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./docker-db/store:/var/lib/mysql
    networks:
      - network

networks:
  network: